version: 2
jobs:
    build:
        docker:
            - image: sumdoc/texlive-2017
        steps:
            - checkout
            - run:
                name: Generating current version
                command: |
                    latexmk -xelatex cv.tex;
                    mkdir /tmp/artifacts;
                    cp cv.pdf /tmp/artifacts/
            - store_artifacts:
                path: /tmp/artifacts